### ISSUE TITLE
Issue when using the plugin with SecurityComponent enabled

### ISSUE THREAD

**Issue by ghost** [uzyn/cakephp-opauth#16]
Enabling this plugin with the Security component in cakephp 2.2.5 results in a 404 / blackholed request on auth/callback.

**Comment by uzyn** [comment]
Can you elaborate further on how you're using it? Maybe share your app-level controllers or any setup so I can reproduce it?

**Comment by ghost** [comment]
@uzyn  Thanks for the reply, my setup is pretty simple.

https://gist.github.com/4536944

Disabling Security component in AppController or beforeFilter fixes the issue.

**Comment by ghost** [comment]
The problem seems to be isolated to POST requests, setting Configure::write('Opauth.callback_transport', 'get') || Configure::write('Opauth.callback_transport', 'session') work as expected.

**Comment by uzyn** [comment]
Thanks for the update @thinkcast. 

Oh well, I changed the default from session to POST due to session messing up with CakePHP's and causing CakePHP's session to be reset. It worked fine but CakePHP's session at the parent site will be reset.

Gotta think of a better way to find a method that works for all.

Thanks!

**Comment by ceeram** [comment]
In 1.0 this issue will not exist anymore, as the callback_transport isnt used anymore, there will be no additional callback anymore. I will close the ticket as with the current version it can be solved with not using POST

**Comment by eswoosh** [comment]
I think this needs reopening
